version: '3'
services:
  angular-ui:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
       - ./front:/usr/src/app/front
    environment:
      - PORT=4200
